version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
    resource_class: large
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
           # echo Configuration
          
    
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
         #start: npx cypress open
         yarn: true
         store_artifacts: true
         record: false
         #command: npx cypress run --e2e
         requires:
          - cypress/install
         parallel: true
         parallelism: 2
         group: 4 machines
