version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/
          #username: $DOCKER_HUB_USER
          #password: $DOCKER_HUB_PASSWORD
    resource_class: medium
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Configuration for the app
          
    
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
         #start: npx cypress open

         yarn: true
         store_artifacts: true

         requires:
          - cypress/install
         parallel: true
         parallelism: 2
         group: 4 machines