version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:    
    resource_class: medium
jobs:
  my-job-name:
    executor: my-custom-executor
    steps: 
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
orbs:
  cypress: cypress-io/cypress@2.2.0

workflows:
  test-cypress-tests:
    jobs:
      - cypress/install
      - cypress/run:
         #executor: my-custom-executor
         command: npx cypress run
         yarn: true
         store_artifacts: true
         requires:
          - cypress/install
         parallel: true
         parallelism: 1
         #command: npx cypress run --env split=true

          
          
         #group: 3 machines